name: "Small Projects with Python"
description: >
  A curated collection of beginner-friendly Python exercises originally
  developed for coursework at Sahand University of Technology.
repository: "https://github.com/RasoulUnlimited/Small-projects-with-python"
license: "MIT"
homepage: "https://rasoulunlimited.ir/projects/python-projects/"
