# Support me by using the funding links below
# Developed and Rasoul Unlimited

custom: ["https://app.jibimo.com/direct/RasoulUnlimited"]
# Your donation means a lot to me to continue the development of open source project like this.
