title: "Small Projects with Python"
description: >
  A curated collection of beginner-friendly Python exercises originally
  developed for coursework at Sahand University of Technology. While simple,
  the examples lay the groundwork for exploration in numerical methods and
  basic AI algorithms.
topics:
  - biomedical-engineering
  - research-software
  - open-science
  - python-tools
  - academic-python
  - zenodo-indexed
  - semantic-scholar
  - scientific-code