[project]
name = "small-projects-with-python"
version = "1.0.0"
authors = [ { name = "Rasol Unlimited" } ]
license = { text = "MIT" }
urls = { "Repository" = "https://github.com/RasoulUnlimited/Small-projects-with-python" }